// <auto-generated />
using System;
using MagicVilla.DataStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250320102527_SeedTableVilla")]
    partial class SeedTableVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Swimming pool, Adventure activities, 2 rooms, 1 Kitchen, Luxury Beds, Luxury furniture",
                            CreatedDate = new DateTime(2025, 3, 20, 15, 55, 26, 606, DateTimeKind.Local).AddTicks(2295),
                            ImageUrl = "",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 400,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Swimming pool, Adventure activities, 2 rooms, 1 Kitchen, Luxury Beds, Luxury furniture",
                            CreatedDate = new DateTime(2025, 3, 20, 15, 55, 26, 606, DateTimeKind.Local).AddTicks(2311),
                            ImageUrl = "",
                            Name = "Serene Villa",
                            Occupancy = 5,
                            Rate = 300.0,
                            Sqft = 600,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Swimming pool, Adventure activities, 2 rooms, 1 Kitchen, Luxury Beds, Luxury furniture",
                            CreatedDate = new DateTime(2025, 3, 20, 15, 55, 26, 606, DateTimeKind.Local).AddTicks(2314),
                            ImageUrl = "",
                            Name = "Heavenly Abode",
                            Occupancy = 3,
                            Rate = 150.0,
                            Sqft = 500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Swimming pool, Adventure activities, 2 rooms, 1 Kitchen, Luxury Beds, Luxury furniture",
                            CreatedDate = new DateTime(2025, 3, 20, 15, 55, 26, 606, DateTimeKind.Local).AddTicks(2315),
                            ImageUrl = "",
                            Name = "Peaceful Oasis",
                            Occupancy = 8,
                            Rate = 300.0,
                            Sqft = 800,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Swimming pool, Adventure activities, 2 rooms, 1 Kitchen, Luxury Beds, Luxury furniture",
                            CreatedDate = new DateTime(2025, 3, 20, 15, 55, 26, 606, DateTimeKind.Local).AddTicks(2317),
                            ImageUrl = "",
                            Name = "Rustic Hideaway",
                            Occupancy = 9,
                            Rate = 300.0,
                            Sqft = 1000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
